language: objective-c
podfile: Tests/Podfile
xcode_workspace: Tests/Tests.xcworkspace
xcode_scheme: Tests
xcode_sdk: iphonesimulator
osx_image: xcode61
before_script:
- sudo easy_install cpp-coveralls
- brew update
- brew upgrade xctool
after_success:
- coveralls
